### PR TITLE
fix: update transaction receipt validation and write test for file up…

### LINKED ISSUE #1040: FEE_SCHEDULE_FILE_PART_UPLOADED marked as error
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to [Hedera](https://hedera.com) or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'Good First Issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahashgraph+archived%3Afalse+label%3A%22Good+First+Issue%22+) is to help you make your first contribution to Hedera.

## 👾 Description of the issue
 - When submitting a `FileUpdate` along with the required `FileAppends` in order to update the `0.0.111` fees file, getting the receipt returns or throws a `ReceiptStatusException`. The `FEE_SCHEDULE_FILE_PART_UPLOADED` response is not an error, but is a response to indicate that the file is not complete and requires more `FileAppends` until a Fees file is fully uploaded.
 
- See https://github.com/hashgraph/hedera-sdk-java/issues/1950

### Steps to reproduce the error

 1.  Create a `FileUpdateTransaction` for file with file id `0.0.111` with the proper fee payer and signatures.
 2. Execute the transaction:
`final var transactionResponse = transaction.execute(client);`
 3. Get the receipt:
`receipt = transactionResponse.getReceipt(client);`

### Additional context
 - This problem was already fixed in Java SDK https://github.com/hashgraph/hedera-sdk-java/pull/1967

### Proposed Solution:
- Add handling in `ValidateStatus` in `transaction_receipt.go`
- Test your change using e2e test in `transaction_receipt_query_e2e_test.go` , similar to the [fix](https://github.com/hashgraph/hedera-sdk-java/pull/1967/files#diff-139e5dc3a1621d612a32143dfbff4e899660d395059a054309916c81cb60804c) in Java

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. More information and concrete samples for shell commands for each step can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md) file.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** Here, it is needed to add `sign-off` information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org). More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)
- [ ] **Start a Pull Request (PR)**: We have a pattern for naming pull requests that a GitHub Action checks. We use that pattern to support the creation of automatic release notes.
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the Hedera developer community for support.
- [ ] **Wait for reviews:** Members of the Hedera developer community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of the Hedera community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional Information

If you have any questions, just ask us directly in this issue by adding a comment. You can join our community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

### PR DESCRIPTION
**Pull request by Mujhtech**
**Description**:

This PR modified validate transaction receipt status to prevent throwing an error when status is StatusFeeScheduleFilePartUploaded

**Related issue(s)**:

Fixes #1040 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: transaction_receipt_query_e2e_test.go [hunk 1]
```diff
@@ -127,3 +127,28 @@ func DisabledTestIntegrationTransactionReceiptQueryInvalidTransactionID(t *testi
 	err = CloseIntegrationTestEnv(env, nil)
 	require.NoError(t, err)
 }
+
+func TestIntegrationFileUpdateTransaction(t *testing.T) {
+	t.Parallel()
+	env := NewIntegrationTestEnv(t)
```
Comment (0xivanov) [inline transaction_receipt_query_e2e_test.go:133]:
```suggestion
	env := NewIntegrationTestEnv(t)
	defer CloseIntegrationTestEnv(env, nil)
```

File: transaction_receipt_query_e2e_test.go [hunk 2]
```diff
@@ -127,3 +127,28 @@ func DisabledTestIntegrationTransactionReceiptQueryInvalidTransactionID(t *testi
 	err = CloseIntegrationTestEnv(env, nil)
 	require.NoError(t, err)
 }
+
+func TestIntegrationFileUpdateTransaction(t *testing.T) {
```
Comment (0xivanov) [inline transaction_receipt_query_e2e_test.go:131]:
```suggestion
func TestIntegrationFileUpdateTransactionHandleFeeScheduleUpload(t *testing.T) {
```

**Review by 0xivanov — APPROVED** [review]
LGTM, nice job!
