### PR TITLE
fix: Add better error handling in test utils

### LINKED ISSUE #943: Add better error handling in utilities for test
### Problem

Methods like `NewIntegrationTestEnv` and `CloseIntegrationTestEnv` might panic ungracefully in certain circumstances.

### Solution

Add better error handling and return the error to the tests.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by 0xivanov**
**Description**:
Methods like `NewIntegrationTestEnv` and `CloseIntegrationTestEnv` might panic ungracefully in certain circumstances.
This PR adds better error handling by adding asserts when error occures.

**Related issue(s)**:

Fixes #943

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by gsstoykov — APPROVED** [review]

File: utilities_for_test.go [hunk 1]
```diff
@@ -154,14 +154,11 @@ func NewIntegrationTestEnv(t *testing.T) IntegrationTestEnv {
...
+
+		require.NoError(t, err)
 
 		receipt, err := resp.SetValidateStatus(true).GetReceipt(env.Client)
-		if err != nil {
-			panic(err)
-		}
+		require.NoError(t, err)
 
 		env.OriginalOperatorID = env.Client.GetOperatorAccountID()
```
Comment (gsstoykov) [inline utilities_for_test.go:163]: Isn't this called for the second time after l.148

File: utilities_for_test.go [hunk 2]
```diff
@@ -154,14 +154,11 @@ func NewIntegrationTestEnv(t *testing.T) IntegrationTestEnv {
...
 		env.OriginalOperatorKey = env.Client.GetOperatorPublicKey()
```
Comment (gsstoykov) [inline utilities_for_test.go:164]: Should we check these values?

File: utilities_for_test.go (hunk 1 above)
Comment (0xivanov) [reply utilities_for_test.go]: Removed the duplication

File: utilities_for_test.go (hunk 2 above)
Comment (0xivanov) [reply utilities_for_test.go]: It's already checked at line 106, but I've added `assert.NotNil(t, env.Client)`

File: utilities_for_test.go [hunk 3]
```diff
@@ -154,17 +155,14 @@ func NewIntegrationTestEnv(t *testing.T) IntegrationTestEnv {
...
 		receipt, err := resp.SetValidateStatus(true).GetReceipt(env.Client)
-		if err != nil {
-			panic(err)
-		}
+		require.NoError(t, err)
 
-		env.OriginalOperatorID = env.Client.GetOperatorAccountID()
-		env.OriginalOperatorKey = env.Client.GetOperatorPublicKey()
+		// env.OriginalOperatorID = env.Client.GetOperatorAccountID()
+		// env.OriginalOperatorKey = env.Client.GetOperatorPublicKey()
```
Comment (agadzhalov) [inline utilities_for_test.go:165]: why do we have to leave these two commented lines here?

Comment (0xivanov) [reply utilities_for_test.go:165]: My bad, forgot to remove them after running the tests. Thanks

**Review by agadzhalov — APPROVED** [review]
LGTM
