### PR TITLE
fix: Retry in case of throttle when calling `getRecord`

### LINKED ISSUE #1125: Fix `THROTTLED_AT_CONSENSUS` for `getRecord`
### Description

`getRecord` can sometimes cause `THROTTLED_AT_CONSENSUS` status and we need to handle it.

### Steps to reproduce

TBD

### Additional context

_No response_

### Hedera network

_No response_

### Version

latest

### Operating system

None

### PR DESCRIPTION
**Pull request by 0xivanov**
**Description**:

**Related issue(s)**:

Fixes #1125

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by gsstoykov — APPROVED** [review]
Looks good. We can rerun the CI integration tests a couple of times just to be safe.

File: transaction_response.go [hunk 1]
```diff
@@ -91,6 +91,10 @@ func (response TransactionResponse) GetRecord(client *Client) (TransactionRecord
 		SetNodeAccountIDs([]AccountID{response.NodeID}).
 		Execute(client)
 
+	for receipt.Status == StatusThrottledAtConsensus {
+		receipt, err = retryTransaction(client, response.Transaction)
+	}
+
```
Comment (gsstoykov) [inline transaction_response.go:97]: Maybe this could be verified with:
Creating a test which constantly tries to get a record of a transaction. But could be a loss of CI time as we have to bake a certain amount of time which we would constantly loop over a transaction being sent and getting its record? WDYT?

Comment (0xivanov) [reply transaction_response.go:97]: Yeah, this would slow down a lot CI time, since the throttles are quite random.
