### PR TITLE
Various fixes

### LINKED ISSUE #809: Various Hedera go sdk issues/inconsistencies found while working on wallet connect support
### Description

While working on a parser I need for all 36 transaction types to support wallet connect, I found a number of issues or inconsistencies. Rather than explain them all here, I have simply submitted unit tests in the attached files. It's possible you may disagree on whether or not a couple of these are defects.

The most important one that I need fixed for the Wallawallet wallet connect release is the one named TestHGoSdkIssue_Incorrectly_Throws_Unsupported_Transaction_Type_Error, where I cannot reconstitute an AccountUpdateTransaction from the transaction bytes. I have not yet attempted to debug this further than my own code.

[HederaSdkDefects_test.go.txt](https://github.com/hashgraph/hedera-sdk-go/files/12689544/HederaSdkDefects_test.go.txt)
[test-util.go.txt](https://github.com/hashgraph/hedera-sdk-go/files/12689545/test-util.go.txt)

I've included relevant portions of the output of running the tests below so you can see at a glance what the issues are:

```
Contents Base64:  
--- FAIL: TestHGoSdkIssue_FileAppendTransaction_Missing_Contents_After_Reconstitution (0.12s)
    HederaSdkDefects_test.go:86: error parsing transaction bytes: Expected to find Contents for FileAppendTransaction, but there were none.
Message Base64:  dGVzdCB0b3BpYyBtZXNzYWdl
Message Base64:  
--- FAIL: TestHGoSdkIssue_TopicMessageSubmitTransaction_Missing_Message_After_Reconstitution (0.12s)
    HederaSdkDefects_test.go:107: error parsing transaction bytes: Expected to find Contents for FileAppendTransaction, but there were none.
Assessment Method:  FeeAssessmentMethodInclusive
--- FAIL: TestHGoSdkIssue_CustomFractionFee_Missing_SetAssessmentMethod_Method (0.00s)
    HederaSdkDefects_test.go:116: There is currently no SetAssessmentMethod() for CustomFractionalFee in golang, but it exists in JS SDK and as far as I can tell is needed
--- FAIL: TestHGoSdkIssue_SystemDeleteTransaction_Type_Inconsistent_For_GetExpirationTime (0.09s)
    HederaSdkDefects_test.go:135: expected GetExpirationTime() to return a time.Time type (as that's what the setter uses), not: int64
--- FAIL: TestHGoSdkIssue_ContractCreateTransaction_Uses_Inconsistent_Type_For_MaxAutomaticTokenAssociations (0.10s)
    HederaSdkDefects_test.go:183: expected GetMaxAutomaticTokenAssociations() for AccountCreateTransaction and ContractCreateTransaction to return value of same type, but instead they were uint32 and int32
--- FAIL: TestHGoSdkIssue_AutoRenewAccount_Not_Correctly_Set_For_TokenCreateTransaction (0.10s)
    HederaSdkDefects_test.go:229: expected autoRenewAccount to be the one that was explictly set, which is 0.0.122837, but got 0.0.2240404
--- FAIL: TestHGoSdkIssue_TopicCreateTransaction_May_Be_Missing_expirationTime_Property (0.00s)
    HederaSdkDefects_test.go:251: The TopicCreateTransaction is missing the expirationTime property, yet the TopicUpdateTransaction has that property. This might be a bug.
FAIL
exit status 1

``` 

### Steps to reproduce

1. Rename the files to .go files
2. My project has just these dependencies: require (
	github.com/hashgraph/hedera-sdk-go/v2 v2.29.0
	github.com/stretchr/testify v1.8.4
	google.golang.org/protobuf v1.31.0
)
3. Once configured, just run "go test", or "go test -v -run <testname>" for an individual test.

### Additional context

_No response_

### Hedera network

testnet

### Version

v2.29.0

### Operating system

macOS

### PR DESCRIPTION
**Pull request by rokn**
**Description**:
- fix serialization issues
- fix auto renew on token create tx
- fix return type on system delete tx

**Related issue(s)**:

Fixes #809 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: system_delete_transaction.go [hunk 1]
```diff
@@ -80,12 +80,12 @@ func (transaction *SystemDeleteTransaction) SetExpirationTime(expiration time.Ti
 }
 
 // GetExpirationTime returns the time at which this transaction will expire.
-func (transaction *SystemDeleteTransaction) GetExpirationTime() int64 {
+func (transaction *SystemDeleteTransaction) GetExpirationTime() time.Time {
```
Comment (bamzedev) [inline system_delete_transaction.go:83]: Is this breaking change necessary?

**Review by bamzedev — APPROVED** [review]
